Feature test evaluator (Unit tests to follow)
hygieia/api-audit pull request #132
Opened 2022-04-08 15:34 UTC by tatlax3636

* Create new feature test evaluator for new FT audit flow

**Affects:** \<api-audit-version-number>.

2022-04-13 19:18 UTC, nameisaravind commented on src/main/java/com/capitalone/dashboard/evaluator/FeatureTestResultEvaluator.java
> +        List<TestResult> testResultList = testResultRepository.findByCollectorItemIdAndTimestampIsBetweenOrderByTimestampDesc(testItem.getId(), 0, System.currentTimeMillis());
Please get test results only with defined data range

2022-04-13 19:18 UTC, nameisaravind commented on src/main/java/com/capitalone/dashboard/evaluator/FeatureTestResultEvaluator.java
> +            LOGGER.warn("Could not parse double from featureTestThreshold. Setting to default value.");
Log as ERROR

2022-04-13 19:18 UTC, nameisaravind commented on src/main/java/com/capitalone/dashboard/evaluator/FeatureTestResultEvaluator.java
> +    private double getTestCasePassPercent(List<TestCapability> testCapabilities) {
add exception handling for this method

2022-04-13 19:18 UTC, nameisaravind commented on src/main/java/com/capitalone/dashboard/evaluator/FeatureTestResultEvaluator.java
> +    protected HashMap getFeatureTestResult(TestResult testResult) {
add exception handling for this method

2022-04-13 19:18 UTC, nameisaravind commented on src/main/java/com/capitalone/dashboard/evaluator/FeatureTestResultEvaluator.java
> +    public boolean isAllTestCasesSkipped(List<TestCapability> testCapabilities) {
add exception handling

2022-04-13 19:18 UTC, nameisaravind commented on src/test/java/com/capitalone/dashboard/evaluator/FeatureTestResultEvaluatorTest.java
> +//    @Test
plz remove the commented lines.

2022-04-13 21:11 UTC, tatlax3636 commented on src/main/java/com/capitalone/dashboard/evaluator/FeatureTestResultEvaluator.java
> +        List<TestResult> testResultList = testResultRepository.findByCollectorItemIdAndTimestampIsBetweenOrderByTimestampDesc(testItem.getId(), 0, System.currentTimeMillis());
Updated to use beginDate and endDate

2022-04-13 21:12 UTC, tatlax3636 commented on src/main/java/com/capitalone/dashboard/evaluator/FeatureTestResultEvaluator.java
> +            LOGGER.warn("Could not parse double from featureTestThreshold. Setting to default value.");
updated

2022-04-13 21:12 UTC, tatlax3636 commented on src/test/java/com/capitalone/dashboard/evaluator/FeatureTestResultEvaluatorTest.java
> +//    @Test
removed file until next PR with unit tests

2022-04-14 20:07 UTC, tatlax3636 commented on src/main/java/com/capitalone/dashboard/evaluator/FeatureTestResultEvaluator.java
> +    public boolean isAllTestCasesSkipped(List<TestCapability> testCapabilities) {
added

2022-04-14 20:07 UTC, tatlax3636 commented on src/main/java/com/capitalone/dashboard/evaluator/FeatureTestResultEvaluator.java
> +    protected HashMap getFeatureTestResult(TestResult testResult) {
added

2022-04-14 20:07 UTC, tatlax3636 commented on src/main/java/com/capitalone/dashboard/evaluator/FeatureTestResultEvaluator.java
> +    private double getTestCasePassPercent(List<TestCapability> testCapabilities) {
added

2022-04-18 16:35 UTC, nireeshT commented on src/main/java/com/capitalone/dashboard/evaluator/FeatureTestResultEvaluator.java
> +import com.capitalone.dashboard.model.*;
refactor imports, dont use *

2022-04-18 16:36 UTC, nireeshT commented on src/main/java/com/capitalone/dashboard/evaluator/FeatureTestResultEvaluator.java
> +        collItemOptions.put("artifactName", identifierName);
use constants for identifierName and identifierVersion

2022-04-18 16:37 UTC, nireeshT commented on src/main/java/com/capitalone/dashboard/evaluator/FeatureTestResultEvaluator.java
> +            }catch(Exception e){
Catch ParseException instead of Exception

2022-04-18 16:40 UTC, nireeshT requested changes
Review comments

2022-04-18 17:04 UTC, tatlax3636 commented on src/main/java/com/capitalone/dashboard/evaluator/FeatureTestResultEvaluator.java
> +        collItemOptions.put("artifactName", identifierName);
done

2022-04-18 17:06 UTC, tatlax3636 commented on src/main/java/com/capitalone/dashboard/evaluator/FeatureTestResultEvaluator.java
> +            }catch(Exception e){
Throws "NumberFormatException", not "ParseException". updated to catch this instead of generic Exception

2022-04-19 13:26 UTC, nireeshT approved these changes
LGTM

2022-04-19 13:26 UTC, merged