code review audit - repo error validation
Hygieia/api-audit pull request #68
Opened 2020-10-19 12:24 UTC by nameisaravind

code review audit - repo error validation done against the time range, pull requests, commits.

2020-10-19 17:35 UTC, rvema requested changes
please address the review comments

2020-10-19 17:35 UTC, rvema commented on src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java
> +            if ((CollectionUtils.isEmpty(pullRequests) && CollectionUtils.isEmpty(commits))) {
this condition can be returned right?

2020-10-19 17:35 UTC, rvema commented on src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java
> +            if ((CollectionUtils.isEmpty(pullRequests) && CollectionUtils.isEmpty(commits))) {
also too many if conditions, can you refactor it?

2020-10-19 18:01 UTC, nameisaravind commented on src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java
> +            if ((CollectionUtils.isEmpty(pullRequests) && CollectionUtils.isEmpty(commits))) {
@rvema yes, it will be returned only if there is a git error within the audit time range, and there is no pull-requests/commits collected within the same audit time range. if conditions updated.

2020-11-05 14:52 UTC, rvema requested changes
please address the review comments.

2020-11-05 14:52 UTC, rvema commented on src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java
> +                && colErrors.stream().anyMatch(err -> isWithinTimeRange(err.getTimestamp(), beginDt, endDt))
too many `&&` in the if condition. please try to refactor

2020-11-05 16:24 UTC, nameisaravind commented on src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java
> +                && colErrors.stream().anyMatch(err -> isWithinTimeRange(err.getTimestamp(), beginDt, endDt))
this is discussed and valid

2020-11-05 17:41 UTC, nameisaravind commented
> please address the review comments.

discussed, no change neeeded

2020-11-05 19:16 UTC, nireeshT approved these changes
LGTM

2020-11-12 17:53 UTC, nireeshT approved these changes
LGTM

2020-11-17 16:27 UTC, rvema approved these changes
lgtm

2020-11-17 16:27 UTC, merged