log the request parameters of GET requests
Hygieia/api-audit pull request #69
Opened 2020-12-03 16:33 UTC by danielyhuang

**Affects:** \<api-audit-version-number>.

2020-12-03 16:36 UTC, nireeshT commented on src/main/java/com/capitalone/dashboard/logging/LoggingFilter.java
> +            String parameters = Collections.list(request.getParameterNames()).stream()
request.getParameterNames() = null, cause NPE

2020-12-03 16:37 UTC, nireeshT requested changes
Review comments

2020-12-03 16:37 UTC, rvema requested changes
please address the minor review comment

2020-12-03 16:37 UTC, rvema commented on src/main/java/com/capitalone/dashboard/logging/LoggingFilter.java
> +                            .map(p -> p + ":" + Arrays.asList( request.getParameterValues(p)) )
please put a null check for request.getParameters MapUtils.isNotEmpty...

2020-12-03 16:49 UTC, danielyhuang commented on src/main/java/com/capitalone/dashboard/logging/LoggingFilter.java
> +            String parameters = Collections.list(request.getParameterNames()).stream()
add a null check for request.getParameters

2020-12-03 16:50 UTC, danielyhuang commented on src/main/java/com/capitalone/dashboard/logging/LoggingFilter.java
> +                            .map(p -> p + ":" + Arrays.asList( request.getParameterValues(p)) )
added

2020-12-03 17:06 UTC, nireeshT approved these changes
LGTM

2020-12-04 18:13 UTC, rvema approved these changes
lgtm

2020-12-04 18:13 UTC, merged